### PR TITLE
Make User Entrypoint Workflow-Centric [minor]

### LINKED ISSUE #25: Make "Workflow" Object and Replace `POST /task/directive` with `POST /workflow/`
This will be a `minor` bump.

A workflow is a collection of task directives, logically linked by common queues.

### Workflow object
This will be the main public-facing object, replacing the current role of the task_directive--replace `POST /task/directive` with `POST /workflow/`.
```
task_directives: < list of task directives >
public_queues: < list of queues determined for public access >
...
```

### Upade task directive object

Add:
- `input_queues`: a list of user-provided aliases for queues (names to be stored in mqs)
- `output_queues`: same as above

Remove:
- `n_queues`
- `queues`

### PR DESCRIPTION
**Pull request by ric-evans**
Now, the user will interact with a "workflow" object, a collection of task directives.

### MQS Updates
To limit redundancy, queue IDs will be (1) generated immediately by MQS on workflow request and (2) stored in the MQS. These queues will be _reserved_ but not created--a flag will be added to the MQS object, `mqprofile`

~### `multiupdate_db_lock` Explanation~
~When inserting a new workflow object into the DB, taskforces must also be inserted. These two object types live in different mongo collections. In the time between these two insertions (one single, one bulk), it is possible for the "mq activator" to find the workflow object and try to augment its taskforces, only for it to find that there are no taskforces (yet). Using a lock around this, and similar actions, prevents such a race condition.~

https://github.com/Observation-Management-Service/ewms-message-queue-service/pull/7

closes #25

### CODE REVIEW

**Comment by ric-evans** [comment]
NOTE: we need clear distinction in terminology between a task (ie the executable/image) and an instance of the task on a worker. What is "multitasking"? This is similar to "image" vs "container"

**Comment by ric-evans** [comment]
TODO: After PR approval, run `ruff check --select C408 --fix . --unsafe-fixes` to convert to literal dict syntax

**Comment by ric-evans** [comment]
In order limit redundancy, queue ids will be (1) generated immediately by MQS on workflow request and (2) stored in the MQS. These queues will be _reserved_ but not created--a flag will be added to the MQS object, `mqprofile`

**Review by dsschult — APPROVED** [review]
LGTM on a quick read through.

**Pull request merged**
